### ISSUE TITLE
 'AppCommand' has no attribute 'option_list'

### ISSUE THREAD

**Issue by DeanKamali** [Brobin/drf-generators#25]
I'm attempting to run the generator for app named "manager" 

`python manage.py generate manager --format modelviewset`

I'm getting the following error 

```
  File "/python/api/lib/python3.5/site-packages/drf_generators/management/commands/generate.py", line 8, in <module>
    class Command(AppCommand):
  File "python/api/lib/python3.5/site-packages/drf_generators/management/commands/generate.py", line 33, in Command
    option_list = AppCommand.option_list + base_options
AttributeError: type object 'AppCommand' has no attribute 'option_list'
```

**Comment by Brobin** [comment]
What django version are you on?

**Comment by DeanKamali** [comment]
@Brobin I found out that it works with django 1.8, 1.9.0 but not with 1.9+ or 1.10

Seems that `option_list` has been [depreciated ](https://docs.djangoproject.com/en/1.8/howto/custom-management-commands/#django.core.management.BaseCommand.option_list)

[](https://docs.djangoproject.com/en/1.8/howto/custom-management-commands/#django.core.management.BaseCommand.option_list)

Docs suggest to use `add_arguments()` instead 

I'm also seeing warning, maybe this should go into enhancement ticket 

```
base.py:265: RemovedInDjango110Warning: OptionParser usage for Django management commands is deprecated, use ArgumentParser instead
  RemovedInDjango110Warning)
```

**Comment by Brobin** [comment]
Ah, yes. We may have to monkey patch this if the same features aren't backward compatible.

**Comment by Brobin** [comment]
Marking as duplicate of #28
